services:
  website1:
    image: wordpress
    ports: 
      - "3100:80"
  website2:
    image: wordpress
    ports: 
      - "3200:80"
    networks:
      wordpress_net:
        ipv4_address: 192.168.99.20

networks:
  wordpress_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.99.0/24"
